# Generated by Django 2.2.4 on 2019-08-13 08:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50000, verbose_name='Post Text Contents')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication time')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('publishedtext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialnet.PublishedText')),
            ],
            bases=('socialnet.publishedtext',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('publishedtext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialnet.PublishedText')),
            ],
            bases=('socialnet.publishedtext',),
        ),
    ]
