# Generated by Django 2.2.1 on 2019-07-31 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Publication time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='Publication time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
