# Generated by Django 2.2.4 on 2019-08-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0002_auto_20190813_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='socialnet.PublishedText'),
        ),
    ]
