# Generated by Django 2.2.1 on 2019-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0003_auto_20190731_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=50000, verbose_name='Post Text Contents'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=50000, verbose_name='Post Text Contents'),
        ),
    ]
